
//菜单
export const GETMENU = "GETMENU"
export const GETMENU_ASYNC = "GETMENU_ASYNC"
export const GETMENU_LIST = "GETMENU_LIST"
export const GETMENULIST_ASYNC = "GETMENULIST_ASYNC"
export const ADDMENU_ASYNC = "ADDMENU_ASYNC"
export const EDITMENU_ASYNC = "EDITMENU_ASYNC"

//用户
export const REGISTER = "REGISTER"
export const LOGIN = "LOGIN"
export const GETUSER = "GETUSER"
export const GETUSER_ASYNC = "GETUSER_ASYNC"
export const ADDUSERROLE_ASYNC = "ADDUSERROLE_ASYNC"

//角色
export const GETROLE = "GETROLE"
export const GETROLE_ASYNC = "GETROLE_ASYNC"
export const ADDROLE_MENU_ASYNC = "ADDROLE_MENU_ASYNC"
export const GETROLELIST = "GETROLELIST"
export const RESETROLELIST = "RESETROLELIST"
export const GETROLELIST_ASYNC = "GETROLELIST_ASYNC"


//文章
export const SAVEARTICLE = "SAVEARTICLE"
export const ADDCATEGORY = "ADDCATEGORY"
export const GETCATEGORY = "GETCATEGORY"
export const GETCATEGORY_ASYNC = "GETCATEGORY_ASYNC"
